version: '3.8'
services:
  drachitio_server:
    container_name: drachitio_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-drachitio
    ports:
      - "5060:5060"
      - "9022:9022"
      - "9021:9021"

  rediss:
    container_name: rediss
    image: redis
    restart: always
    ports:
      - "6379:6379"


